package com.pos.crypto_pay_kt.ui.theme

import androidx.compose.ui.graphics.Color

val Navy = Color(0xFF0B2557)
val NavyLight = Color(0xFFAFC6FF)
val Teal = Color(0xFF007A70)
val TealLight = Color(0xFF5EEAD4)
val LightBackground = Color(0xFFF7F8FA)
val LightSurface = Color(0xFFFFFFFF)
val DarkBackground = Color(0xFF111318)
val DarkSurface = Color(0xFF191C22)
val Error = Color(0xFFB3261E)
val LightPrimaryContainer = Color(0xFFDCE5FF)
val LightOnPrimaryContainer = Color(0xFF061A3A)
val LightSecondaryContainer = Color(0xFFB8ECE5)
val LightOnSecondaryContainer = Color(0xFF00201C)
val LightOutline = Color(0xFF74777F)
val LightOutlineVariant = Color(0xFFC4C6CF)
val DarkPrimaryContainer = Color(0xFF183D70)
val DarkOnPrimaryContainer = Color(0xFFDCE5FF)
val DarkSecondaryContainer = Color(0xFF005048)
val DarkOnSecondaryContainer = Color(0xFFB8ECE5)
val Warning = Color(0xFFB26A00)
val WarningContainer = Color(0xFFFFDDB8)
